arrowParens: avoid
bracketSpacing: false
phpVersion: '8.2'
singleQuote: true
tailwindStylesheet: 'resources/client/app.css'
tailwindFunctions: ['cn', 'cva', 'clsx']

plugins:
  - '@prettier/plugin-php'
  - 'prettier-plugin-tailwindcss'

overrides:
  - files: '*.html'
    options:
      printWidth: 100
      tabWidth: 2
      singleQuote: false
  - files: '*.php'
    options:
      tabWidth: 4
